# Generated by Django 3.0.5 on 2020-04-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('user_password', models.CharField(max_length=128)),
                ('user_name', models.CharField(max_length=32)),
                ('create_data', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
