# Generated by Django 3.0.5 on 2020-04-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
