# .travis.yml

language: python
branches:
  only:
    - master
python:
  - "3.6"
install:
  - pip install -r requirements.txt
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # 사용하기 전에 Travis-ci 에서 setting의 환경변수로 설정한 값. AWS IAM 에서 설정한 Access Key, Secret
    secret_access_key: $AWS_ASECRET_KEY
    bucket: phas-django
    region: ap-northeast-2 # S3 resion
    skip_cleanup: true
    acl: private
    local_dir: deploy # deploy 디렉터리에 있는 파일을 S3로 업로드 하겠다는 뜻

#python:
#    - "3.5"
#    - "3.6"
#
#dist: trusty
#sudo: rquired
#
#env:
#    - DJANGO_VERSION==2.0
#
#
#install:
#    - pip3 install -q Django=$DJANGO_VERSION
#    - pip3 install -q -r requirements.txt
#
#script:
#    - cd for_hg
#    - touch problem/secrets.py
#    - echo "AWS_ACCESS_KEY_ID=''" >> problem/secrets.py
#    - echo "AWS_SECRET_ACCESS_KEY=''" >> problem/secrets.py
#    - python3 manage.py migrate
#    - python3 -m pytest -n 3 --cov-config .coveragerc --cov=.