# Generated by Django 3.0.5 on 2020-04-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartbeat',
            name='audio_file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
