# Generated by Django 2.0.13 on 2020-04-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20200427_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogInfo',
            fields=[
                ('dog_idx', models.AutoField(primary_key=True, serialize=False)),
                ('dog_breed', models.CharField(max_length=64)),
                ('dog_name', models.CharField(max_length=32)),
                ('dog_size', models.PositiveSmallIntegerField()),
                ('dog_birth', models.DateTimeField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserInfo')),
            ],
        ),
    ]
