# Generated by Django 2.0.13 on 2020-04-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doginfo',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='doginfo',
            name='dog_idx',
        ),
        migrations.AlterField(
            model_name='doginfo',
            name='dog_name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
