# Generated by Django 2.0.13 on 2020-04-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20200428_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doginfo',
            name='dog_birth',
            field=models.DateField(),
        ),
    ]
